server:
    port: 8888

spring:
    application:
        name: "config-server"
    cloud:
        config:
            server: 
                git:
                    uri: "https://github.com/Ajsalemo/azure-spring-apps-development"
                    searchPaths:
                    - '/config'

