cloud:
    name: "ansalemo-springboot (8)"

spring:
    jmx:
        enabled: true
    cloud:
         config:
          auto-refresh: true
          refresh-interval: 60
        
management:
    endpoints:
        jmx:
            exposure:
                include: '*'
        web:
            exposure:
                include: 
                - refresh

