# Uncomment to run locally
# Comment this out to run on Azure Spring Apps
# spring:
#     application:
#         name: "ansalemo-springboot"
#     config:
#         import: "optional:configserver:http://localhost:8888"

cloud:
    name: "ansalemo-springboot (local)"

spring:
    jmx:
        enabled: true
    cloud:
         config:
          auto-refresh: true
          refresh-interval: 60
        
management:
    endpoints:
        jmx:
            exposure:
                include: '*'
        web:
            exposure:
                include: 
                - refresh