# Uncomment to run locally
# Comment this out to run on Azure Spring Apps
spring:
    application:
        name: "ansalemo-eureka-client"
#     config:
#         import: "optional:configserver:http://localhost:8888"

cloud:
    name: "ansalemo-springboot (local)"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  tomcat:
    mbeanregistry:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG

eureka:
  client:
    registryFetchIntervalSeconds: 2000


